# Generated by Django 2.2.6 on 2019-10-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_img', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_description', models.CharField(max_length=5000)),
            ],
        ),
    ]
